---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: oel65-chef-java

suites:
  - name: default
    run_list:
      - recipe[omc_zookeeper::default]
    attributes:
      java:
         install_flavor: 'oracle'
         jdk_version: '8'
         oracle:
           accept_oracle_download_terms: true

