---
driver:
  name: docker
  http_proxy: http://den00bjg.us.oracle.com:8124
  https_proxy: http://den00bjg.us.oracle.com:8124

driver_config:
  sudo: false
  use_sudo: false
  require_chef_omnibus: 11.16.4
  image: oracle/oel67:1.0

provisioner:
  name: chef_zero
  use_sudo: false
  client_rb:
    http_proxy: http://den00bjg.us.oracle.com:8124
    https_proxy: http://den00bjg.us.oracle.com:8124
    no_proxy: localhost,127.0.0.1

platforms:
- name: oel
  driver_config:
    sudo: false
    use_sudo: false
    require_chef_omnibus: 11.16.4
    image: oracle/oel67:1.0
    platform: rhel
    hostname: default-oel65-chef-java
    forward:
      - 2181:2181

suites:
  - name: default
    environments_path: "test/integration/environments"
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[omc_zookeeper_test::default]
      - recipe[test-helper::default]
    attributes:
      java:
         install_flavor: 'oracle'
         jdk_version: '8'
         oracle:
           accept_oracle_download_terms: true
      omc_zookeeper:
        home: '/opt/zk_home'
        source_url: 'http://www.us.apache.org/dist/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz'
        version: '3.4.6'
        install_path: '/opt/zookeeper'
        data_path: '/data/zookeeper/data'
        log_path: '/var/log/zookeeper'
        config_path: '/opt/zookeeper/conf'
        ensemble_data_bag_info:
          slapchop: 'zookeeper_localdev'
        client_port: 2182,
        quorum_port: 2888,
        leader_port: 3888,
        service_name: 'zookeeper'
        override_config: {}
