---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  environments_path: "test/integration/environments"
  data_bags_path: "test/integration/data_bags" 
  client_rb:
    environment: localdev

#platforms:
#   - name: oel65-chef-java

platforms:
  - name: chef11
    driver:
      vm_hostname: default-oel65-chef-java
      box: oel65-chef-java
    provisioner:
      require_chef_omnibus: 11.16.4
  - name: chef12
    driver:
      vm_hostname: default-oel65-chef-java
      box: oel65-chef-java
    provisioner:
      require_chef_omnibus: 12.11.18

suites:
  - name: default
    run_list:
      - recipe[omc_zookeeper_test::default]
